Test copy images

diff --git a/.github/workflows/Test statistic.yml b/.github/workflows/Test statistic.yml
--- a/.github/workflows/Test statistic.yml
+++ b/.github/workflows/Test statistic.yml
@@ -25,5 +25,9 @@ jobs:
       - name: Run test copy images
         run: |
           pytest test_copy_image.py
-          echo $?
+          exit_code = $?
+          if [[ exit_code == 0]]; then
+            echo "✅ Copy images test was completed successfully!"
+          else
+            echo "❌ Copy images test was failed!"
           
