Test copy images

diff --git a/.github/workflows/Test disko.yml b/.github/workflows/Test disko.yml
--- a/.github/workflows/Test disko.yml
+++ b/.github/workflows/Test disko.yml
@@ -5,7 +5,35 @@ on:
     branches: [ "ygal" ]
 
 jobs:
-  build:
+  TestStatistic:
+    runs-on: ubuntu-latest
+
+    env:
+      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
+
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Installing requirements
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Run test copy images
+        run: |
+          pytest test_statistic.py
+          echo "✅ Statistic test was completed successfully!"
+          # exit_code=$?
+          # if [ $exit_code -eq "0" ]; then
+          #   echo "✅ Copy images test was completed successfully!"
+          # else
+          #   echo "❌ Copy images test was failed!"
+          # fi
+
+  TestCopyImages:
     runs-on: ubuntu-latest
 
     env:
